### PR TITLE
Pretend status code as 200 (cache)

### PR DESCRIPTION
**Pull request by edwardxia**
This PR fix a bug where http_code is missing thus the headers take place of the status code and all the parameters after http_code got messed up as well.

### CODE REVIEW

**Comment by rohan-achar** [comment]
Oops. Nice catch.

**Comment by rohan-achar** [comment]
I changed 200 to stored value. So please pull.

**Comment by edwardxia** [comment]
Oh. I did not read through the code and assumed only 200 was cached.
I checked the code and I think for the purpose of this crawler, only 2xx, 3xx, and 4xx should be cached. 5xx codes are server side errors the can potentially be recovered at later time, so they should not be cached.

**Comment by rohan-achar** [comment]
Good point. Will make that change

**Pull request merged**
