### PR TITLE
Get rid of duplicate URLs in successful_urls.txt

### PR DESCRIPTION
**Pull request by edwardxia**
This RP ensures that duplicate URLs are not added to `successful_urls.txt`.

### CODE REVIEW

**Comment by rohan-achar** [comment]
This isnt particularly required. When crawler restarts the urls are put into a set again that removes duplicates. The check of how many urls are downloaded is going to only be on the count on that set. Not the number of lines in the url txt.

**Comment by edwardxia** [comment]
@lordnahor You forgot to consider that case that when the crawler crash and user continue the process. The global `url_count` does filter out unique, but when you write the urls to the files, it's possible to have duplicates from the previous run.

**Comment by rohan-achar** [comment]
When the crawler crashes and they start the process again.
https://github.com/Mondego/spacetime/blob/IR_student_crawler/python/applications/search/crawler_frame.py#L21 should ensure that only the unique ones are going to be taken up. The set operation should weed out the duplicates.

**Comment by rohan-achar** [comment]
I dont think im missing an angle where it can fail.

**Comment by edwardxia** [comment]
@lordnahor The global `url_count` does filter out unique, but you are **appending** new urls regardless of whether they are in the file (you did not check that).

**Comment by rohan-achar** [comment]
I do not see why it matters that there are duplicates in the file being written out to disk.

**Comment by edwardxia** [comment]
It simply confuses people.

**Comment by rohan-achar** [comment]
Ahh. ok. If that is the reason.

**Pull request merged**
